export interface BibleBookInfo {
  name: string;
  bookNumber: number;
  chapters: number;
  testament: 'old' | 'new';
  abbreviation: string;
}

export const BIBLE_BOOKS: BibleBookInfo[] = [
  // Old Testament
  { name: 'Genesis', bookNumber: 1, chapters: 50, testament: 'old', abbreviation: 'Gen' },
  { name: 'Exodus', bookNumber: 2, chapters: 40, testament: 'old', abbreviation: 'Exod' },
  { name: 'Leviticus', bookNumber: 3, chapters: 27, testament: 'old', abbreviation: 'Lev' },
  { name: 'Numbers', bookNumber: 4, chapters: 36, testament: 'old', abbreviation: 'Num' },
  { name: 'Deuteronomy', bookNumber: 5, chapters: 34, testament: 'old', abbreviation: 'Deut' },
  { name: 'Joshua', bookNumber: 6, chapters: 24, testament: 'old', abbreviation: 'Josh' },
  { name: 'Judges', bookNumber: 7, chapters: 21, testament: 'old', abbreviation: 'Judg' },
  { name: 'Ruth', bookNumber: 8, chapters: 4, testament: 'old', abbreviation: 'Ruth' },
  { name: '1 Samuel', bookNumber: 9, chapters: 31, testament: 'old', abbreviation: '1Sam' },
  { name: '2 Samuel', bookNumber: 10, chapters: 24, testament: 'old', abbreviation: '2Sam' },
  { name: '1 Kings', bookNumber: 11, chapters: 22, testament: 'old', abbreviation: '1Kgs' },
  { name: '2 Kings', bookNumber: 12, chapters: 25, testament: 'old', abbreviation: '2Kgs' },
  { name: '1 Chronicles', bookNumber: 13, chapters: 29, testament: 'old', abbreviation: '1Chr' },
  { name: '2 Chronicles', bookNumber: 14, chapters: 36, testament: 'old', abbreviation: '2Chr' },
  { name: 'Ezra', bookNumber: 15, chapters: 10, testament: 'old', abbreviation: 'Ezra' },
  { name: 'Nehemiah', bookNumber: 16, chapters: 13, testament: 'old', abbreviation: 'Neh' },
  { name: 'Esther', bookNumber: 17, chapters: 10, testament: 'old', abbreviation: 'Esth' },
  { name: 'Job', bookNumber: 18, chapters: 42, testament: 'old', abbreviation: 'Job' },
  { name: 'Psalms', bookNumber: 19, chapters: 150, testament: 'old', abbreviation: 'Ps' },
  { name: 'Proverbs', bookNumber: 20, chapters: 31, testament: 'old', abbreviation: 'Prov' },
  { name: 'Ecclesiastes', bookNumber: 21, chapters: 12, testament: 'old', abbreviation: 'Eccl' },
  { name: 'Song of Solomon', bookNumber: 22, chapters: 8, testament: 'old', abbreviation: 'Song' },
  { name: 'Isaiah', bookNumber: 23, chapters: 66, testament: 'old', abbreviation: 'Isa' },
  { name: 'Jeremiah', bookNumber: 24, chapters: 52, testament: 'old', abbreviation: 'Jer' },
  { name: 'Lamentations', bookNumber: 25, chapters: 5, testament: 'old', abbreviation: 'Lam' },
  { name: 'Ezekiel', bookNumber: 26, chapters: 48, testament: 'old', abbreviation: 'Ezek' },
  { name: 'Daniel', bookNumber: 27, chapters: 12, testament: 'old', abbreviation: 'Dan' },
  { name: 'Hosea', bookNumber: 28, chapters: 14, testament: 'old', abbreviation: 'Hos' },
  { name: 'Joel', bookNumber: 29, chapters: 3, testament: 'old', abbreviation: 'Joel' },
  { name: 'Amos', bookNumber: 30, chapters: 9, testament: 'old', abbreviation: 'Amos' },
  { name: 'Obadiah', bookNumber: 31, chapters: 1, testament: 'old', abbreviation: 'Obad' },
  { name: 'Jonah', bookNumber: 32, chapters: 4, testament: 'old', abbreviation: 'Jonah' },
  { name: 'Micah', bookNumber: 33, chapters: 7, testament: 'old', abbreviation: 'Mic' },
  { name: 'Nahum', bookNumber: 34, chapters: 3, testament: 'old', abbreviation: 'Nah' },
  { name: 'Habakkuk', bookNumber: 35, chapters: 3, testament: 'old', abbreviation: 'Hab' },
  { name: 'Zephaniah', bookNumber: 36, chapters: 3, testament: 'old', abbreviation: 'Zeph' },
  { name: 'Haggai', bookNumber: 37, chapters: 2, testament: 'old', abbreviation: 'Hag' },
  { name: 'Zechariah', bookNumber: 38, chapters: 14, testament: 'old', abbreviation: 'Zech' },
  { name: 'Malachi', bookNumber: 39, chapters: 4, testament: 'old', abbreviation: 'Mal' },
  
  // New Testament
  { name: 'Matthew', bookNumber: 40, chapters: 28, testament: 'new', abbreviation: 'Matt' },
  { name: 'Mark', bookNumber: 41, chapters: 16, testament: 'new', abbreviation: 'Mark' },
  { name: 'Luke', bookNumber: 42, chapters: 24, testament: 'new', abbreviation: 'Luke' },
  { name: 'John', bookNumber: 43, chapters: 21, testament: 'new', abbreviation: 'John' },
  { name: 'Acts', bookNumber: 44, chapters: 28, testament: 'new', abbreviation: 'Acts' },
  { name: 'Romans', bookNumber: 45, chapters: 16, testament: 'new', abbreviation: 'Rom' },
  { name: '1 Corinthians', bookNumber: 46, chapters: 16, testament: 'new', abbreviation: '1Cor' },
  { name: '2 Corinthians', bookNumber: 47, chapters: 13, testament: 'new', abbreviation: '2Cor' },
  { name: 'Galatians', bookNumber: 48, chapters: 6, testament: 'new', abbreviation: 'Gal' },
  { name: 'Ephesians', bookNumber: 49, chapters: 6, testament: 'new', abbreviation: 'Eph' },
  { name: 'Philippians', bookNumber: 50, chapters: 4, testament: 'new', abbreviation: 'Phil' },
  { name: 'Colossians', bookNumber: 51, chapters: 4, testament: 'new', abbreviation: 'Col' },
  { name: '1 Thessalonians', bookNumber: 52, chapters: 5, testament: 'new', abbreviation: '1Thess' },
  { name: '2 Thessalonians', bookNumber: 53, chapters: 3, testament: 'new', abbreviation: '2Thess' },
  { name: '1 Timothy', bookNumber: 54, chapters: 6, testament: 'new', abbreviation: '1Tim' },
  { name: '2 Timothy', bookNumber: 55, chapters: 4, testament: 'new', abbreviation: '2Tim' },
  { name: 'Titus', bookNumber: 56, chapters: 3, testament: 'new', abbreviation: 'Titus' },
  { name: 'Philemon', bookNumber: 57, chapters: 1, testament: 'new', abbreviation: 'Phlm' },
  { name: 'Hebrews', bookNumber: 58, chapters: 13, testament: 'new', abbreviation: 'Heb' },
  { name: 'James', bookNumber: 59, chapters: 5, testament: 'new', abbreviation: 'Jas' },
  { name: '1 Peter', bookNumber: 60, chapters: 5, testament: 'new', abbreviation: '1Pet' },
  { name: '2 Peter', bookNumber: 61, chapters: 3, testament: 'new', abbreviation: '2Pet' },
  { name: '1 John', bookNumber: 62, chapters: 5, testament: 'new', abbreviation: '1John' },
  { name: '2 John', bookNumber: 63, chapters: 1, testament: 'new', abbreviation: '2John' },
  { name: '3 John', bookNumber: 64, chapters: 1, testament: 'new', abbreviation: '3John' },
  { name: 'Jude', bookNumber: 65, chapters: 1, testament: 'new', abbreviation: 'Jude' },
  { name: 'Revelation', bookNumber: 66, chapters: 22, testament: 'new', abbreviation: 'Rev' },
];
